### ISSUE TITLE
Not seeing port 2080 connection in docker for smartthings mqtt bridge

### ISSUE THREAD

**Issue by kdubmisc** [vkorn/hassio-addons#1]
Hi,
I configured the smartthings ide to point to the smartthings mqtt bridge, but I don't see any events or activities in the events.log.  I'm think the port is not listening in the docker even though the logs says it is listening to port 2080.
e.g.:

starting version 3.2.2
info: Starting SmartThings MQTT Bridge - v1.3.4
info: Loading configuration
info: Loading previous state
info: Perfoming configuration migration
info: Saving current state
info: Connecting to MQTT at mqtt://192.168.1.117:1883
info: Configuring autosave
info: Configuring API
info: Listening at http://localhost:2080

**Here's the result from running "docker ps":**
![image](https://user-images.githubusercontent.com/9296309/28858950-2cfaf808-7709-11e7-96a4-020eff9930b0.png)
Notice the first record does not have any port listening activities.  But the other dockers have it open.

**Here's my config.yml file settings using hassio.io IDE screen:**
{
  "broker_host": "192.168.1.117",
  "broker_port": 1883,
  "preface": "smartthings",
  "state_suffix": "state",
  "command_suffix": "cmd",
  "login": "********",
  "password": "*******",
  "bridge_port": 2080
}

Should I see port open for 2080 when i run 'docker ps' command?

**Comment by vkorn** [comment]
Hey @kdubmisc, 

This addon is using host network, without explicit ports binding, so no, you won't see it in ps output

Sometimes it happens that you have to re-save your configuration in ST IDE to make it work with new installation (power-cycle hub may also help).

**Comment by kdubmisc** [comment]
Thanks @vkorn !  I've gotten better progress now.  I got smartthings app to talk ;  but from HA to smartthings is not working.   I need to keep troubleshooting to see why.  Thanks for your help!
