### ISSUE TITLE
Can't start PS4 Addon

### ISSUE THREAD

**Issue by outrun0506** [vkorn/hassio-addons#14]
He, I'm not able to start PS4-Addon

Log shows no entry. When I click start, nothing happens.

Heres my config:

{
  "port": 3031,
  "devices": [
    {
      "client_type": "i",
      "auth_type": "C",
      "credentials": "XXXX"
    }
  ]

**Comment by elmurato** [comment]
I can confirm this. Running on Hass.io 0.57.2.

**Comment by outrun0506** [comment]
Supervisor Logs saying:

`17-12-03 17:48:06 ERROR (SyncWorker_9) [hassio.dock] Can't create container from addon_e5829d31_ps4waker -> 409 Client Error: Conflict ("Conflict. The container name "/addon_e5829d31_ps4waker" is already in use by container "14829d3a7810a6d18f12a9fc9206068bb852fa380bb58ed72d7e9dd5b9bfc464". You have to remove (or rename) that container to be able to reuse that name.")`

- Uninstall
- Restart HASSIO
- Reinstall

does not fix the Problem

docker ps does not show the PS4 Plugin

`671fbcafa7d1        homeassistant/raspberrypi3-homeassistant   "/usr/bin/entry.sh..."   About an hour ago   Up About an hour                                                     homeassistant
5df1d1d82bc3        ceecc69e/armhf-addon-unifi                 "/usr/bin/java -Xm..."   About an hour ago   Up About an hour                                                     addon_ceecc69e_unifi
663e28b82f6a        homeassistant/armhf-addon-rpc_shutdown     "/usr/bin/entry.sh..."   About an hour ago   Up About an hour                                                     addon_core_rpc_shutdown
6f3704cde42d        hassioaddons/ssh-armhf                     "/init"                  About an hour ago   Up About an hour                                                     addon_a0d7b954_ssh
ce33d376606f        homeassistant/armhf-addon-samba            "/usr/bin/entry.sh..."   About an hour ago   Up About an hour                                                     addon_core_samba
2d85832a883f        homeassistant/armhf-addon-mosquitto        "/usr/bin/entry.sh..."   About an hour ago   Up About an hour    0.0.0.0:1883->1883/tcp, 0.0.0.0:8883->8883/tcp   addon_core_mosquitto
a3c6e5eff635        homeassistant/armhf-hassio-supervisor      "/usr/bin/entry.sh..."   8 days ago          Up About an hour                                                     resin_supervisor
`

**Comment by outrun0506** [comment]
I found a fix for that:

What you need is debug access to hassio:
https://home-assistant.io/developers/hassio/debugging/

Check your supervisor log's for folder-name of the addon
e.g.: 14829d3a7810a6d18f12a9fc9206068bb852fa380bb58ed72d7e9dd5b9bfc464

Uninstall the AddOn

Login to Debug-Hassio via SSH

go to directory: /var/lib/docker/containers/

Here you should find your AddOn Folder.

Delete this folder.
Reboot hassio (not shure if need, but i did)
Reinstall AddOn
Configure AddOn
Enjoy working AddOn :-)

BR

Lukas
